[versions]
activityVersion = "1.9.3"
androidXCoreKtxVersion = "1.15.0"
androidXAppCompatVersion = "1.7.0"
androidXConstraintLayoutVersion = "2.2.0"

gsonVersion = "2.11.0"
jsoupVersion = "1.18.3"
timberVersion = "5.0.1"
assentVersion = "3.0.2"
materialVersion = "1.12.0"
materialNumberPickerVersion = "1.0.5"
circulardurationviewVersion = "1.1.4"

junitVersion = "4.13.2"
androidxJunitVersion = "1.2.1"
androidXEspressoCoreVersion = "3.6.1"

kotlinVersion = "2.2.21"
androidApplicationVersion = "8.7.3"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCoreKtxVersion" }
androidxAppCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidXAppCompatVersion" }
androidxConstraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidXConstraintLayoutVersion" }

gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoupVersion" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }
assent = { module = "com.afollestad.assent:core", version.ref = "assentVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
materialNumberPicker = { module = "com.github.StephenVinouze:MaterialNumberPicker", version.ref = "materialNumberPickerVersion" }
circulardurationview = { module = "com.github.abdalmoniem:CircularDurationView", version.ref = "circulardurationviewVersion" }

junit = { group = "junit", name = "junit", version.ref = "junitVersion" }
androidxJunit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunitVersion" }
androidxEspressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidXEspressoCoreVersion" }

[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
androidApplication = { id = "com.android.application", version.ref = "androidApplicationVersion" }
