#file: noinspection Annotator
name: Build Debug Variant
run-name: ${{ github.workflow }} ${{ github.event.repository.updated_at}}

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '00 00 * * 5'

permissions: { }

jobs:
  build-debug-variant:
    name: Build Debug Variant
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create local.properties
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > release_keystore.jks

          keystoreFile=$(realpath release_keystore.jks)

          echo "keystoreFile: $keystoreFile"

          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties
          echo "keyAlias=release_key" >> local.properties
          echo "storeFile=$keystoreFile" >> local.properties

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2.1.3

      - name: Build Debug APK
        run: bash gradlew app:assembleDebug

      - name: Get Debug APK Name
        run: |
          debugApk=$(find app/build/outputs/apk/debug/*.apk)
          echo $debugApk
          echo ARTIFACT_NAME=$(basename $debugApk) >> $GITHUB_ENV
          echo ARTIFACT_PATH=$debugApk >> $GITHUB_ENV

      - name: Create Artifact ${{ env.ARTIFACT_NAME }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
          if-no-files-found: error
